version: "3.7"

services:

  api:
    container_name: code-processing-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://code-processing-db:5432/code-processing
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  code-processing-db:
    container_name: code-processing-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=code-processing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
